export const TESTS_MIGRATED_TO_VITEST = [
    "packages/ui-common/__tests__/components/AgentChat/ChatCommon/ChatCommon.test.tsx",
    "packages/ui-common/__tests__/components/Authentication/Auth.test.tsx",
    "packages/ui-common/__tests__/components/ChatBot/ChatBot.test.tsx",
    "packages/ui-common/__tests__/components/ErrorPage/ErrorBoundary.test.tsx",
    "packages/ui-common/__tests__/components/Settings/FadingCheckmark.test.tsx",
    "packages/ui-common/__tests__/components/Settings/SettingsDialog.test.tsx",
    "packages/ui-common/__tests__/components/Settings/SettingsRow.test.tsx",
    "packages/ui-common/__tests__/unit/AgentChat/Utils.test.ts",
    "packages/ui-common/__tests__/unit/Controller/agent/Agent.test.ts",
    "packages/ui-common/__tests__/unit/Controller/agent/IconSuggestions.test.ts",
    "packages/ui-common/__tests__/unit/Theme/Theme.test.ts",
    "packages/ui-common/__tests__/unit/Utils/Authentication.test.ts",
    "packages/ui-common/__tests__/unit/Utils/BrowserNavigation.test.ts",
    "packages/ui-common/__tests__/unit/Utils/File.test.ts",
    "packages/ui-common/__tests__/unit/Utils/text.test.ts",
    "packages/ui-common/__tests__/unit/Utils/zIndexLayers.test.ts",
]
