---
name: Checkmarx One

on:
    schedule:
        # M-F at 2:30 am UTC (offset from neuro-san to avoid contention)
        - cron: "30 2 * * 1-5"
    workflow_dispatch:

jobs:
    checkmarx:
        # build-common 1.0.11
        uses: cognizant-ai-lab/build-common/.github/workflows/_checkmarx.yml@a70df67b0d623e56f34159de26c38989cd315d26
        with:
            base-uri: ${{ vars.CX_BASE_URI }}
            cx-tenant: ${{ vars.CX_TENANT }}
            cx-client-id: ${{ vars.CX_CLIENT_ID }}
        secrets:
            CX_CLIENT_SECRET: ${{ secrets.CX_CLIENT_SECRET }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        permissions:
            contents: write
            security-events: write
